### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by wzurborg** [blizzhackers/d2data#1]
Hi, this is great work and very helpful. Are there any plans for localization or is there any work ongoing? I guess it would just require an additional language mapping.

**Comment by Nishimura-Katsuo** [comment]
I don't have plans to localize it, but there's not much to localize in the d2data json files themselves. The example apps I made to consume the data are just examples, so I don't plan to localize those.

**Comment by Nishimura-Katsuo** [comment]
I've generated locale strings for different languages, and that's the extend of the localization. Most strings in the data files aren't externally-facing strings, so that will be the extend of the localization efforts.
